version: '3'

volumes:
  postgres_volume:

networks:
    mylocal:
        driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mylocal
  db:
    image: postgres:15-alpine
    container_name: "postgres_db"
    restart: always
    env_file: geo.env
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - mylocal
