version: '3'

volumes:
  postgres_user_volume:
  postgres_geo_volume:

networks:
    mylocal:
        driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mylocal
  db_user:
    image: postgres:15-alpine
    container_name: "db_user"
    restart: always
    env_file: user.env
    ports:
      - "54321:5432"
    volumes:
      - postgres_user_volume:/var/lib/postgresql/data
    networks:
      - mylocal
  db_geo:
    image: postgres:15-alpine
    container_name: "db_geo"
    restart: always
    env_file: geo.env
    ports:
      - "54322:5432"
    volumes:
      - postgres_geo_volume:/var/lib/postgresql/data
    networks:
      - mylocal
